<?php

namespace TemperBundle\Repository;

/**
 * UserCohortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCohortRepository extends \Doctrine\ORM\EntityRepository
{
}
